# **MÓDULO 15 - Exercício**
# Análise  - A segunda etapa da Pré Modelagem

# 1) O primeiro exercício é o de salvar a base que criaram na atividade do módulo anterior em csv e abrir ela neste arquivo.
Igual fizemos no início do módulo atual no início da primeira aula.

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import plotly.express as px

In [23]:
#Seu código de importação aqui
# Realizamos o salvamento do arquivo CSV na ultima execução da tarefa do módulo 14
# pode ser consultado no link a seguir:

# Abrindo o arquivo csv
df = pd.read_csv(r'..\Pratica\CHURN_TELECON_MOD15_TAREFA.csv', delimiter=',')

# verificando os dados em conformindade ao módulo 14
df.head(15)

,customerID,Gender,Elderly,Married,Dependents,Time_as_a_customer,PhoneService,Internet_Service,Security_Service,Technical_Support,StreamingTV,Contract_type,Payment_Method,Monthly_Payment,Total_Paid,Churn
0,7590-VHVEG,f,0,1,0,1,0.0,dsl,0,0,0,month-to-month,electronic check,29.850000,29.85,0.0
1,5575-GNVDE,m,0,0,0,34,1.0,dsl,1,0,0,one year,mailed check,56.950000,1889.50,0.0
2,3668-QPYBK,m,0,0,0,2,1.0,dsl,1,0,0,month-to-month,mailed check,53.850000,108.15,1.0
3,7795-CFOCW,m,0,0,0,45,0.0,dsl,1,1,0,one year,bank transfer (automatic),65.607563,1840.75,0.0
4,8191-XWSZG,f,0,0,0,52,1.0,no,0,0,0,one year,mailed check,65.607563,1022.95,0.0
5,9959-WOFKT,m,0,0,1,71,1.0,fiber optic,1,0,1,two year,bank transfer (automatic),65.607563,7382.25,0.0
6,4190-MFLUW,f,0,1,1,10,1.0,dsl,0,1,0,month-to-month,credit card (automatic),65.607563,528.35,1.0
7,4183-MYFRB,f,0,0,0,21,1.0,fiber optic,0,0,0,month-to-month,electronic check,65.607563,1862.90,0.0
8,8779-QRDMV,m,1,0,0,1,0.0,dsl,0,0,0,month-to-month,electronic check,65.607563,39.65,1.0
9,1680-VDCWW,m,0,1,0,12,1.0,no,0,0,0,one year,bank transfer (automatic),65.607563,202.25,0.0
10,1066-JKSGK,m,0,0,0,1,1.0,no,0,0,0,month-to-month,mailed check,65.607563,20.15,1.0
11,3638-WEABW,f,0,1,0,58,1.0,dsl,0,1,0,two year,credit card (automatic),65.607563,3505.10,0.0
12,6322-HRPFA,m,0,1,1,49,1.0,dsl,1,1,0,month-to-month,credit card (automatic),65.607563,2970.30,0.0
13,6865-JZNKO,f,0,0,0,30,1.0,dsl,1,0,0,month-to-month,bank transfer (automatic),65.607563,1530.60,0.0
14,6467-CHFZW,m,0,1,1,47,1.0,fiber optic,0,0,1,month-to-month,electronic check,65.607563,4749.15,1.0

# 2) Comece pela análise univariada:

### A) Utilize a função describe no seu dataframe, veja os insights que consegue retirar.

### B) Já é possível identificar variáveis com possíveis outliers? Se sim, quais?

In [24]:
#Seu código aqui

# A) Utilize a função describe no seu dataframe, veja os insights que consegue retirar.
# B) Já é possível identificar variáveis com possíveis outliers? Se sim, quais?
df.describe()

,Elderly,Married,Dependents,Time_as_a_customer,PhoneService,Security_Service,Technical_Support,StreamingTV,Monthly_Payment,Total_Paid,Churn
count,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000
mean,0.161576,0.492765,0.314711,32.352090,0.965434,0.284164,0.285772,0.385852,65.607563,2290.087178,0.260048
std,0.368135,0.500048,0.464494,24.636885,0.182714,0.451106,0.451872,0.486894,27.984700,2264.585643,0.438749
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.400000,18.800000,0.000000
25%,0.000000,0.000000,0.000000,8.000000,1.000000,0.000000,0.000000,0.000000,45.400000,402.337500,0.000000
50%,0.000000,0.000000,0.000000,29.000000,1.000000,0.000000,0.000000,0.000000,65.607563,1402.900000,0.000000
75%,0.000000,1.000000,1.000000,56.000000,1.000000,1.000000,1.000000,1.000000,87.712500,3867.162500,1.000000
max,1.000000,1.000000,1.000000,72.000000,1.000000,1.000000,1.000000,1.000000,118.650000,8564.750000,1.000000

#### Insights que podemos retirar da execução do método describe()
- Podemos confirmar que não existem dados nulos na amostra
- 'PhoneService' apresenta uma alta taxa de adesão, porém, pode ser um dados com viés, isso se deve ao fato de que na primeira etapa do processamento, atribuímos a moda para preencher os dados vazios. anteriormente, mais de 59% da base não apresentava dados nessa coluna.
- Existe um desvio padrão bem significativo nas colunas 'Time_as_a_customer', 'Monthly_Payment' e 'Total_Paid'
- Podemos validar que aproximadamente metade dos clientes são casados.

#### Outliers
- Podemos identificar outliers nas colunas 'Time_as_a_customer', 'Monthly_Payment' e 'Total_Paid'
- Indicamos estes variáveis pois o desvio padrão muito elevado 
    - Time_as_a_customer: 24.636885018004264
    - Monthly_Payment: 27.984699694698094
    - Total_Paid: 2264.5856430075414
- O que apresenta maior evidencia de outliers é a variável 'Total_Paid'

### C) Plot gráficos que considerar importante para completar sua análise univariada. (Lembrando que sua variável preditora é o churn). Não se esqueça de trazer insights de cada gráfico plotado. Utilize pelo menos 4 variáveis distintas.

Insights
- Aproximadamente 74% dos clientes não apresentam intenção de deixar a companhia telefônica
- 78% dos clientes tem serviço de internet, divididos em DSL(33.8%) e Fibra Ótica(45%)
- 21% dos clientes não tem serviço de internet, o que pode indicar que tenham contrato de telefonia ou que já não estão utilizando nenhum serviço
- O tipo de contrato predominante com a empresa de telefonia é o mensal (Pagamento mensal)
- Aproximadamente 68% dos clientes não têm dependentes

In [25]:
# C) Plot gráficos que considerar importante para completar sua análise univariada. 
# (Lembrando que sua variável preditora é o churn). 
# Não se esqueça de trazer insights de cada gráfico plotado. 
# Utilize pelo menos 4 variáveis distintas.

# Gráfico 1: Distribuição da variável 'Churn'
# contagem de churn
count_churn = df['Churn'].value_counts()
print(f'Contagem de Churn:\n{count_churn}')
# Calcular a porcentagem de churn
percent_churn = (count_churn / count_churn.sum()) * 100
print(f'Percentual de Churn:\n{percent_churn}')
# Gráfico de barras
fig = px.bar(
    count_churn, 
    x=percent_churn.index, 
    y=percent_churn.values,)
fig.update_layout(
    title='Distribuição de Churn (em %)',
    xaxis_title='Churn',
    yaxis_title='Porcentagem',
    xaxis=dict(tickvals=[0, 1], ticktext=['Não', 'Sim']),
    yaxis=dict(title='Porcentagem'),
    showlegend=False
)
fig.show()

Contagem de Churn:
Churn
0.0    1841
1.0     647
Name: count, dtype: int64
Percentual de Churn:
Churn
0.0    73.995177
1.0    26.004823
Name: count, dtype: float64

In [26]:
# Grãfico 2: Distribuição de serviços de internet
count_Internet_Service = df['Internet_Service'].value_counts()
print(count_Internet_Service)
# Calcular a porcentagem de churn
percent_Internet_Service = (count_Internet_Service / count_Internet_Service.sum()) * 100
print(percent_Internet_Service)
# Gráfico de barras
fig = px.pie(
    percent_Internet_Service, 
    names=percent_Internet_Service.index, 
    values=count_Internet_Service.values,
    title='Distribuição de Serviços de Internet (em %) ')
fig.update_traces(textposition='inside', textinfo='label+percent')

fig.show()

Internet_Service
fiber optic    1119
dsl             842
no              527
Name: count, dtype: int64
Internet_Service
fiber optic    44.975884
dsl            33.842444
no             21.181672
Name: count, dtype: float64

In [28]:
# Gráfico 3: Distribuição do tipo de contrato
count_Contract_type = df['Contract_type'].value_counts()
print(count_Contract_type)
# Calcular a porcentagem de churn
percent_Contract_type = (count_Contract_type / count_Contract_type.sum()) * 100
print(percent_Contract_type)
# Gráfico de barras
fig = px.pie(
    percent_Contract_type, 
    names=percent_Contract_type.index, 
    values=count_Contract_type.values,
    title='Distribuição de Tipos de contrato (em %) ')
fig.update_traces(textposition='inside', textinfo='label+percent')

fig.show()

Contract_type
month-to-month    1369
two year           602
one year           517
Name: count, dtype: int64
Contract_type
month-to-month    55.024116
two year          24.196141
one year          20.779743
Name: count, dtype: float64

In [29]:
# Gráfico 4: Distribuição de Dependentes
# contagem de churn
count_dpt = df['Dependents'].value_counts()
print(f'Contagem de Churn:\n{count_dpt}')
# Calcular a porcentagem de churn
percent_dpt = (count_dpt / count_dpt.sum()) * 100
print(f'Percentual de Churn:\n{percent_dpt}')
# Gráfico de barras
fig = px.bar(
    count_dpt, 
    x=percent_dpt.index, 
    y=percent_dpt.values,)
fig.update_layout(
    title='Distribuição de Dependentes (em %)',
    xaxis_title='Dependentes',
    yaxis_title='Porcentagem',
    xaxis=dict(tickvals=[0, 1], ticktext=['Não', 'Sim']),
    yaxis=dict(title='Porcentagem'),
    showlegend=False
)
fig.show()

Contagem de Churn:
Dependents
0    1705
1     783
Name: count, dtype: int64
Percentual de Churn:
Dependents
0    68.528939
1    31.471061
Name: count, dtype: float64

### D) Verifique se os dados das variáveis Booleanas são balanceados ou não.

As variáveis booleanas nesta amostra são:
- Elderly
- Married
- Dependents
- PhoneService
- Security_Service
- Technical_Support
- StreamingTV
- Churn

Já verificamos os dados de 'Dependents' e 'Churn' e podemos dizer que essas variáveis não são balanceadas

Para facilitar o processo, vamos criar uma função para gerar os gráficos.

Observando os gráficos gerados, apenas a variável 'Married' apresenta um grau de balanceamento elevado. Nenhuma das outra variáveis estão balanceadas
Majoritariamente temos:
- Pessoas mais com idade inferior a 60 anos
- Possuem serviço telefônico
- Não possuem serviço de segurança contratado
- Já utilizaram, em algum momento, o suporte técnico da empresa
- Não possuem o serviço de Streaming do provedor

In [ ]:
def plot_distribuicao_boll(df, column_name):
    """
    Gera um gráfico de barras mostrando a distribuição de uma variável booleana no dataframe.

    Parâmetros:
    df (pd.DataFrame): DataFrame contendo a variável booleana.
    column_name (str): Nome da variável booleana a ser analisada.

    Retorno:
    Exibe um gráfico de barras com a distribuição da variável selecionada.
    """
    # Contagem de valores
    count_values = df[column_name].value_counts()
    print(f'Contagem de {column_name}:\n{count_values}')
    
    # Calcular a porcentagem
    percent_values = (count_values / count_values.sum()) * 100
    print(f'Percentual de {column_name}:\n{percent_values}')
    
    # Criando gráfico de barras
    fig = px.bar(
        count_values, 
        x=count_values.index, 
        y=count_values.values
    )
    
    fig.update_layout(
        title=f'Distribuição de {column_name}',
        xaxis_title=column_name,
        yaxis_title='Contagem',
        xaxis=dict(tickvals=[0, 1], ticktext=['Não', 'Sim']),
        yaxis=dict(title='Contagem'),
        showlegend=False
    )
    
    fig.show()

In [ ]:
plot_distribuicao_boll(df, "Elderly")
plot_distribuicao_boll(df, "Married")
plot_distribuicao_boll(df, "PhoneService")
plot_distribuicao_boll(df, "Security_Service")
plot_distribuicao_boll(df, "Technical_Support")
plot_distribuicao_boll(df, "StreamingTV")

Contagem de Elderly:
Elderly
0    2086
1     402
Name: count, dtype: int64
Percentual de Elderly:
Elderly
0    83.842444
1    16.157556
Name: count, dtype: float64

Contagem de Married:
Married
0    1262
1    1226
Name: count, dtype: int64
Percentual de Married:
Married
0    50.723473
1    49.276527
Name: count, dtype: float64

Contagem de PhoneService:
PhoneService
1.0    2402
0.0      86
Name: count, dtype: int64
Percentual de PhoneService:
PhoneService
1.0    96.543408
0.0     3.456592
Name: count, dtype: float64

Contagem de Security_Service:
Security_Service
0    1781
1     707
Name: count, dtype: int64
Percentual de Security_Service:
Security_Service
0    71.583601
1    28.416399
Name: count, dtype: float64

Contagem de Technical_Support:
Technical_Support
0    1777
1     711
Name: count, dtype: int64
Percentual de Technical_Support:
Technical_Support
0    71.42283
1    28.57717
Name: count, dtype: float64

Contagem de StreamingTV:
StreamingTV
0    1528
1     960
Name: count, dtype: int64
Percentual de StreamingTV:
StreamingTV
0    61.414791
1    38.585209
Name: count, dtype: float64

# 3) Identifique e trate as colunas que contém outliers.
Caso opte por mante-los ou altera-los justifique sua escolha.

Tomando como base os os insigths da primeira atividade, foram identificados possiveis outliers 
- Time_as_a_customer: 24.636885018004264
- Monthly_Payment: 27.984699694698094
- Total_Paid: 2264.5856430075414
- O que apresenta maior evidencia de outliers é a variável 'Total_Paid'

Avaliação

Apesar de apresentar um desvio padrão elevado, não forma considerados outliers na avaliação dos graficos de box plot.
Isso de deve pela natureza dos dados que podem variar, como o tempo de permanencia do cliente com algum vinculo e o pagamento mensal.
O Total pago também leva em consideração o valor pago pelo tempo de contrato.
Neste caso vamos manter as os dados como estão.

In [51]:
#Seu código aqui
def plot_box_outliers(df, columns_name):
    """
    Plota boxplots para as colunas especificadas em um DataFrame.

    Args:
        df (pd.DataFrame): DataFrame contendo os dados.
        columns_name (list): Lista de nomes das colunas a serem plotadas.

    Returns:
        None
    """
    # montando o gráfico com plotly
    fig = px.box(df, y=columns_name)
    fig.update_layout(
        title=f'Boxplot de {columns_name}',
        yaxis_title=columns_name,
        xaxis_title='Valores',
        showlegend=False
    )
    # Exibindo o gráfico
    fig.show()

plot_box_outliers(df,"Time_as_a_customer")
plot_box_outliers(df,"Monthly_Payment")
plot_box_outliers(df,"Total_Paid")

# 4) Realize a etapa da análise bivariada:
#### A) Questione pelo menos 5 informações e traga as respostas utilizando visuais gráficos e insights.

**Serviço de internet X Churn**
Observamos que o serviço de internet por fibra óptica, apresenta o maior número de clientes que deram churn no contrato com a empresa.
Possivelmente em função de preço ou qualidade do serviço. Isso se baseia no serviço de dsl que apresenta um número muito menor de desvinculados com a empresa de telecom.
Notamos também que pessoas que não têm serviços de internet, tendem a manter seu contrato com a empresa.

**Tipo de contrato X Churn**
Observamos que o tipo de contrato influencia muito no churn, contratos mensais têm maior probabilidade de apresentar churn no decorrer da vida útil do cliente na base
diferentemente de cliente que tem algum tipo de contrato mais longo, o que podemos indicar uma maior facilidade de mudança para a concorrência por ter contrato mensal.

**Estado Civil X Churn**
Vimos que a quantidade de casados e solteiros apresenta um balanceamento na base, também podemos notar que, clientes solteiros apresentam maior churn que clientes casados, fatores como custo de vida  e estabilidade financeira podem refletir mais negativamente sobre clientes solteiros, influenciando o churn.

**Tempo como cliente X Churn**
Sem dúvida, esse é um ponto muito importante a ser destacado. Podemos conferir que o maior número de churn acontece no primeiro e segundo mês de contrato com a empresa de telecom.
Inversamente, clientes mais antigos tendem a permanecer com a operadora (A partir de 5 anos de contrato),o que leva a uma necessidade de avaliar melhor a motivação de tantos cancelamentos nestes dois primeiros meses.
Pode ser algo relacionado a qualidade do serviço, suporte, disponibilidade de serviço de internet do cliente.

**Gênero X Churn**
Avaliando a questão de genero na amostra, não podemos afirmar que existe uma relevancia entre um sexo ou outro.
Ambos apresentam uma proporção de churn muito equivalentes. Não se mostrando relevante para uma análise mais profunda da causa raiz do problema

In [ ]:
#Seu código aqui
# Serviço de internet X Churn
# Agrupando os dados por tipo de serviço de internet e churn
churn_by_Internet_Service = df.groupby(['Internet_Service', 'Churn']).size().reset_index(name='Count')
    
# Plotando o gráfico de barras
fig = px.bar(
    churn_Internet_Service, 
    x='Internet_Service', 
    y='Count', 
    color='Churn', 
    barmode='group',
    title='Distribuição de Churn por Tipo de Serviço de Internet'
    )
    
fig.update_layout(
    xaxis_title='Tipo de Serviço de Internet',
    yaxis_title='Contagem',
    xaxis=dict(tickvals=[0, 1, 2], ticktext=['DSL', 'Fibra Óptica', 'Sem Internet']),
    showlegend=True
)
    
fig.show()

In [ ]:
#Tipo de contrato X Churn
# Agrupando os dados por tipo de contrato e churn
churn_by_Contract_type = df.groupby(['Contract_type', 'Churn']).size().reset_index(name='Count')
# Plotando o gráfico de barras
fig = px.bar(
    churn_by_Contract_type, 
    x='Contract_type', 
    y='Count', 
    color='Churn', 
    barmode='group',
    title='Distribuição de Churn por Tipo de Contrato'
)
fig.update_layout(
    xaxis_title='Tipo de Contrato',
    yaxis_title='Contagem',
    xaxis=dict(tickvals=[0, 1, 2], ticktext=['Mensal', 'Anual', 'Bianual']),
    showlegend=True
)
fig.show()

In [ ]:
# Estado Civil X Churn
# Agrupando os dados por estado civil e churn
churn_by_Married = df.groupby(['Married', 'Churn']).size().reset_index(name='Count')
# Plotando o gráfico de barras
fig = px.bar(
    churn_by_Married, 
    x='Married', 
    y='Count', 
    color='Churn', 
    barmode='group',
    title='Distribuição de Churn por Estado Civil'
)
fig.update_layout(
    xaxis_title='Estado Civil',
    yaxis_title='Contagem',
    xaxis=dict(tickvals=[0, 1], ticktext=['Solteiro', 'Casado']),
    showlegend=True
)
fig.show()

In [58]:
# tempo como cliente X Churn
# Agrupando os dados por tempo como cliente e churn 
churn_by_time_as_customer = df.groupby(['Time_as_a_customer', 'Churn']).size().reset_index(name='Count')
# Plotando o gráfico de barras
fig = px.bar(
    churn_by_time_as_customer, 
    x='Time_as_a_customer', 
    y='Count', 
    color='Churn', 
    barmode='group',
    title='Distribuição de Churn por Tempo como Cliente'
)   

fig.show()

In [59]:
# Gênero X Churn
# Agrupando os dados por gênero e churn
churn_by_Gender = df.groupby(['Gender', 'Churn']).size().reset_index(name='Count')
# Plotando o gráfico de barras
fig = px.bar(
    churn_by_Gender, 
    x='Gender', 
    y='Count', 
    color='Churn', 
    barmode='group',
    title='Distribuição de Churn por Gênero'
)
fig.update_layout(
    xaxis_title='Gênero',
    yaxis_title='Contagem',
    xaxis=dict(tickvals=['f', 'm'], ticktext=['Feminio', 'Masculino']),
    showlegend=True
)
fig.show()

#### B) Quais variáveis você acredita serem as mais importantes para esse projetos relacionadas a variável Churn?